import type { CmsCollection, CmsField } from "netlify-cms-core";

export const multichainProjects: CmsCollection = {
  name: "multichain-projects",
  label: "Multichain (Projects)",
  folder: "lido-landing/multichain/projects",
  create: true,
  slug: "{{fields.id}}",
  summary: `{{fields.name}}`,
  sortable_fields: [],
  view_filters: undefined,
  fields: [
    {
      name: "id",
      widget: "uuid",
      hide: true,
    } as unknown as CmsField,
    {
      label: "Logo",
      name: "logo",
      widget: "svg",
    } as unknown as CmsField,
    { label: "Name", name: "name", widget: "string" },
    {
      label: "Dscription",
      name: "description",
      widget: "object",
      collapsed: true,
      fields: [
        { label: "Text", name: "text", widget: "string" },
        {
          label: "'Learn More' Link",
          name: "learnMoreLink",
          widget: "string",
          required: false,
        },
      ],
    },
    { label: "TVL Key", name: "tvlId", widget: "string", required: false },
    { label: "Defi Llama Link", name: "defiLlamaLink", widget: "string" },
    { label: "Network Type", name: "networkType", widget: "string" },
    { label: "Stack", name: "stack", widget: "string" },
    {
      label: "Get Links",
      name: "getLinks",
      widget: "object",
      collapsed: true,
      fields: [
        { label: "Token name", name: "tokenName", widget: "string" },
        {
          label: "Buy link",
          name: "buyLink",
          widget: "string",
          required: false,
        },
        {
          label: "Swap link",
          name: "swapLink",
          widget: "string",
          required: false,
        },
        { label: "Bridge link", name: "bridgeLink", widget: "string" },
      ],
    },
    {
      label: "Tooltip Links",
      name: "tooltipLinks",
      widget: "object",
      collapsed: true,
      fields: [
        {
          label: "Snapshot Vote Link",
          name: "snapshotVoteLink",
          widget: "string",
          required: false,
        },
        {
          label: "NEC decision post link",
          name: "necDecisionPostLink",
          widget: "string",
          required: false,
        },
        {
          label: "Deployed Addresses Link",
          name: "deployedAddressesLink",
          widget: "string",
          required: false,
        },
      ],
    },
    {
      label: "Ecosystem Projects",
      name: "ecosystemProjects",
      widget: "relation",
      collection: "ecosystem-projects",
      searchFields: ["name"],
      valueField: "id",
      displayFields: ["name"],
      multiple: true,
      max: 3,
      options_length: 1000,
      required: false,
    } as unknown as CmsField,
    {
      label: "Ecosystem Filters",
      name: "ecosystemFilters",
      widget: "object",
      collapsed: true,
      fields: [
        {
          label: "Network",
          name: "network",
          widget: "relation",
          collection: "ecosystem-config",
          file: "project",
          searchFields: ["networks.*.label"],
          valueField: "networks.*.id",
          displayFields: ["networks.*.label"],
          required: false,
        } as unknown as CmsField,
        {
          label: "Tokens",
          name: "tokens",
          widget: "relation",
          collection: "ecosystem-config",
          file: "project",
          searchFields: ["tokens.*.label"],
          valueField: "tokens.*.id",
          displayFields: ["tokens.*.label"],
          multiple: true,
          required: false,
        } as unknown as CmsField,
      ],
    },
    { label: "Feature", name: "feature", widget: "boolean", default: false },
  ],
};
