name: Tests and Checks

on: pull_request

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master

  actions:
    uses: lidofinance/linters/.github/workflows/actions.yml@master

  code:
    runs-on: ubuntu-latest
    name: Lint and build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run quick checks
        # -e allows running all commands without stopping execution if any intermediate fails
        run: set -e; { yarn format && yarn lint && yarn types }; set +e

      - name: Build
        run: yarn build

